### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by xhm1001** [dpm1002/GESPRO_PracticaGestionTareas_2021#37]
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb

**Comment by dpm1002** [comment]
![image](https://user-images.githubusercontent.com/74177098/100524713-98abb500-31ba-11eb-93da-f5e0a747fabc.png)
